export const mockUsers = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'password123', // plaintext password will be hashed on save
    role: 'applicant',
    profile: {
      phone: '123-456-7890',
      location: 'New York, USA',
      bio: 'Software Developer passionate about web technologies.',
    },
  },
  {
    name: 'Alice Smith',
    email: 'alice.smith@example.com',
    password: 'securePass456',
    role: 'recruiter',
    profile: {
      phone: '234-567-8901',
      location: 'London, UK',
      bio: 'Experienced recruiter specializing in tech hiring.',
      company: 'TechCorp Ltd.',
      position: 'Senior HR Manager',
    },
  },
  {
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    password: 'myPassword789',
    role: 'applicant',
    profile: {
      phone: '345-678-9012',
      location: 'San Francisco, USA',
      bio: 'Frontend developer with a passion for creating responsive designs.',
    },
  },
  {
    name: 'Sophia Williams',
    email: 'sophia.williams@example.com',
    password: 'strongPass987',
    role: 'recruiter',
    profile: {
      phone: '456-789-0123',
      location: 'Berlin, Germany',
      bio: 'Tech recruiter with expertise in building diverse teams.',
      company: 'DevSearchers',
      position: 'Talent Acquisition Specialist',
    },
  },
  {
    name: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    password: 'password321',
    role: 'applicant',
    profile: {
      phone: '567-890-1234',
      location: 'Chicago, USA',
      bio: 'Full-stack developer with 5 years of experience in MERN stack.',
    },
  },
  {
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    password: 'Pass4567',
    role: 'recruiter',
    profile: {
      phone: '678-901-2345',
      location: 'Sydney, Australia',
      bio: 'Specialist in hiring cloud technology experts.',
      company: 'CloudHire Pty Ltd.',
      position: 'HR Consultant',
    },
  },
  {
    name: 'Liam Wilson',
    email: 'liam.wilson@example.com',
    password: 'securePassword123',
    role: 'applicant',
    profile: {
      phone: '789-012-3456',
      location: 'Toronto, Canada',
      bio: 'Backend developer skilled in Node.js and database management.',
    },
  },
  {
    name: 'Olivia Thomas',
    email: 'olivia.thomas@example.com',
    password: 'strongPass456',
    role: 'recruiter',
    profile: {
      phone: '890-123-4567',
      location: 'Paris, France',
      bio: 'Hiring manager with a focus on AI and machine learning roles.',
      company: 'InnovateAI',
      position: 'Lead Recruiter',
    },
  },
  {
    name: 'Noah Martin',
    email: 'noah.martin@example.com',
    password: 'developerPass789',
    role: 'applicant',
    profile: {
      phone: '901-234-5678',
      location: 'Tokyo, Japan',
      bio: 'Mobile app developer proficient in Flutter and Swift.',
    },
  },
  {
    name: 'Charlotte Garcia',
    email: 'charlotte.garcia@example.com',
    password: 'recruiterPass123',
    role: 'recruiter',
    profile: {
      phone: '012-345-6789',
      location: 'Madrid, Spain',
      bio: 'Recruiter focused on hiring UI/UX design professionals.',
      company: 'DesignHire Co.',
      position: 'HR Manager',
    },
  },
];
